/*
 * Eyantra_solution.c
 *
 * Created: 1/4/2016 1:49:05 AM
 *  Author: ABHISHEK ACHARYA :)
 */
//V1.2
//improvement in rotation(no longer rotate in only one direction)
//improvement in node traversal (Bot will select shortest path)
#define __OPTIMIZE__ -O0
#define F_CPU 14745600
#define max_node 25
#define th_color 1300
#include <avr/io.h>
#include <avr/interrupt.h>
#include <util/delay.h>
#include <stdlib.h>
#include <math.h> //included to support power function
#include "lcd.h"
volatile unsigned long int l_encode = 0; //to keep track of left position encoder
volatile unsigned long int r_encode = 0; //to keep track of right position encoder
volatile unsigned int digital[16]; // digital value of 16 ADC channel
volatile int ser1=180,ser2=180;
volatile long double xpos=0,ypos=0,tempx=0,tempy=0;
char *navi_pointer;
int navi=180;
int node_num=0,pre_node,r_node=0,found,colo_found=0;
char graph[max_node][max_node];
char p[max_node+1],path[max_node+1];
int path_index=0;
int que_length=0;
char Area='\0',bridge='\0',colo='\0';
volatile int A=1,B=1,C=1,IP=3;
char color[3],color_dep[3];
int color_index=0;
int task1=0,task2=0,task3=0;
int w1=2,w2=2,w3=2,w4=2,w5=2;
int check=0;
volatile unsigned long int pulse = 0; //to keep the track of the number of pulses generated by the color sensor
volatile unsigned long int red;       // variable to store the pulse count when read_red function is called
volatile unsigned long int blue;      // variable to store the pulse count when read_blue function is called
volatile unsigned long int green;

struct queue    //first in first out system
{
	struct queue *next;
	struct queue *prev;
	int num;
}*root=NULL,*end=NULL;


void struct_config(void)
{
	cli();
	def();
	graph[0][1]='N';
	graph[0][2]='S';
	graph[0][6]='E';
	graph[0][10]='W';
	graph[1][0]='S';
	graph[2][0]='N';
	graph[2][3]='S';
	graph[2][4]='W';
	graph[3][2]='N';
	graph[3][5]='W';
	graph[4][2]='E';
	graph[5][3]='E';
	graph[6][0]='W';
	graph[6][19]='N';
	graph[6][18]='S';
	graph[7][19]='W';
	graph[7][20]='E';
	graph[8][20]='N';
	graph[9][18]='W';
	graph[10][0]='E';
	graph[10][11]='N';
	graph[10][13]='S';
	graph[10][16]='W';
	graph[11][14]='E';
	graph[11][10]='S';
	graph[11][12]='N';
	graph[12][15]='W';
	graph[12][11]='S';
	graph[13][10]='N';
	graph[13][17]='W';
	graph[14][11]='W';
	graph[15][12]='E';
	graph[16][10]='E';
	graph[17][13]='E';
	graph[19][7]='E';
	graph[19][6]='S';
	graph[18][6]='N';
	graph[18][9]='E';
	graph[20][8]='S';
	graph[20][7]='W';
	graph[7][21]='N';
	graph[8][22]='E';
	graph[9][23]='S';
	graph[21][7]='S';
	graph[22][8]='W';
	graph[23][9]='N';
	sei();
}
void def(void)
{
	int i=0,j=0;
	for(i=0;i<=max_node;i++)
	for(j=0;j<=max_node;j++)
	graph[i][j]='\0';
}
int path_logic(int curr_node, int req_node) //path find main logic
{
	if(curr_node==req_node && found==0)
	{
		found++;
		return(1);
	}
	int j,r=0;
	for(j=0;j<max_node;j++)
	{
		if(graph[curr_node][j]!='\0' && pre_node!=j)
		{
			p[path_index]=graph[curr_node][j];
			path_index=path_index+1;
			pre_node=curr_node;
			r=r+path_logic(j,req_node);
		}
	}
	if(r>0)
	{
		return(1);
	}
	else
	{
		path_index--;
		return(0);
	}
}
void path_find(int req_node) //path find pre and post operations
{
	int i;
	if(node_num==8 && req_node==23)
	{
		path[1]='S';
		path[2]='W';
		path[3]='S';
		path[4]='\0';
		path_index=1;
	}
	else if(path[path_index]=='\0')
	{
		cli();
		r_node=req_node;
		pre_node=node_num;
		for(i=0;i<max_node+1;i++)
		path[i]='\0';
		path_index=1;
		found=0;
		path_logic(node_num,req_node);
		path_index--;
		for(i=0;i<=max_node+1;i++)
		{
			path[i]='\0';
		}
		for(i=1;i<=path_index;i++)
		{
			path[i]=p[i];
		}
		path_index=1;
		i=1;
		while(path[path_index]!='\0')
		{
			if(path[i]=='E' && path[i+1]=='W')
			path_index=path_index+2;
			path[i]=path[path_index];
			i++;
			path_index++;
		}
		for(path_index=i;path_index<=max_node+1;path_index++)
		path[path_index]='\0';
		path_index=1;
		i=1;
		while(path[path_index]!='\0')
		{
			if((path[i]=='S' && path[i+1]=='N') || (path[i]=='N' && path[i+1]=='S'))
			path_index=path_index+2;
			path[i]=path[path_index];
			i++;
			path_index++;
		}
		for(path_index=i;path_index<=max_node+1;path_index++)
		path[path_index]='\0';
		path_index=1;
		i=1;
		while(path[path_index]!='\0')
		{
			if(path[i]=='W' && path[i+1]=='E')
			path_index=path_index+2;
			path[i]=path[path_index];
			i++;
			path_index++;
		}
		for(path_index=i;path_index<=max_node+1;path_index++)
		path[path_index]='\0';
		path_index=1;
		sei();
	}
	else
	{
		enqueue(req_node);
	}
}
void enqueue(int a)
{
	struct queue *newnode;
	if(root==NULL)
	{
		root=(struct queue*)malloc(sizeof(struct queue));
		root->num=a;
		root->next=NULL;
		root->prev=NULL;
		end=root;
	}
	else
	{
		newnode=(struct queue*)malloc(sizeof(struct queue));
		newnode->num=a;
		root->next=newnode;
		newnode->prev=root;
		root=root->next;
		newnode->next=NULL;
	}
	que_length++;
}
void enq_end(int a)
{
	struct queue *newnode;
	if(end==NULL)
	{
		end=(struct queue*)malloc(sizeof(struct queue));
		end->num=a;
		end->next=NULL;
		end->prev=NULL;
		root=end;
	}
	else
	{
		newnode=(struct queue*)malloc(sizeof(struct queue));
		newnode->num=a;
		end->prev=newnode;
		newnode->next=end;
		end=end->prev;
		newnode->prev=NULL;
	}
	que_length++;
}
void dequeue(void)
{
	if(que_length!=0)
	{
		struct queue *newnode;
		newnode=end;
		end=end->next;
		free(newnode);
		que_length--;
	}
	else
	return;
}
void buzzer(int a)
{
	DDRC=0xFF;  //Buzzer is connected to pin no 3 of port c
	if(a==1)
	PORTC=PORTC|0b00001000;
	else if(a==0)
	PORTC=PORTC|0b00000000;
}
void lcd_port_config (void)
{
	cli();
	DDRC = DDRC | 0xF7; //all the LCD pin's direction set as output
	PORTC = PORTC & 0x80; // all the LCD pins are set to logic 0 except PORTC 7
	sei();
}
void motion(char a)
{
	DDRA=DDRA | 0X0F; // Port A pin no 0,1,2,3 are for motion controlling
	if(a=='f')
	PORTA=0b00000110;
	else if(a=='b')
	PORTA=0b00001001;
	else if(a=='l')
	PORTA=0b00000101;
	else if(a=='r')
	PORTA=0b00001010;
	else if('s')
	PORTA=0x00;
}
void raftaar_config(void)
{
	cli();
	DDRA=DDRA|0x0F;
	DDRL=DDRL | 0b00011000; // declaring pin mo Pl3 and Pl4 as output
	PORTL=PORTL|0b00011000; // if oc pins are disconnected than output Will be one at these pins
	TCNT5=0x00FF; // initial value of counter
	TCCR5A=TCCR5A | 0b10101001; // Timer counter control register
	TCCR5B=TCCR5B | 0b00001011;
	raftaar(255,249);
	sei();
}
void raftaar(unsigned int l,unsigned int r) // a=for left motor and b for right motor
{
	cli();
	OCR5A=l;      // output compare register
	OCR5B=r;
	sei();
}
ISR(INT4_vect)//Interrupt subroutine
{
	int i=0;
	l_encode++;
	if(abs(navi)==360)
	navi=0;
	for(i=0;i<16;i++)
	digital[i]=getdata(i);
}
ISR(INT5_vect) // Interrupt subroutine
{
	int i=0;
	r_encode++;
	if(abs(navi)==360)
	navi=0;
	for(i=0;i<16;i++)
	digital[i]=getdata(i);
}
void distance(char a,float cm,char c)
{
	tempx=xpos;
	tempy=ypos;
	raftaar(255,249);
	float b=0;
	r_encode=0; //clearing encoder value
	l_encode=0;
	while((ceil(b))<(cm))
	{
		if(a=='f')
		{
			PORTA=0b00000110;
		}
		else if(a=='b')
		{
			PORTA=0b00001001;

		}
		b=0.5413*r_encode; // feedback constant value
	}
	stop();
	r_encode=0;
	r_encode=0;
	xpos=tempx;
	ypos=tempy;
	if(c=='w')
	{
		if(a=='f')
		{
		if(*navi_pointer=='E')
		xpos=xpos+cm;
		else if(*navi_pointer=='W')
		xpos=xpos-cm;
		else if(*navi_pointer=='N')
		ypos=ypos+cm;
		else if(*navi_pointer=='S')
		ypos=ypos-cm;

		}
	else if(a=='b')
		{
		if(*navi_pointer=='E')
		xpos=xpos-cm;
		else if(*navi_pointer=='W')
		xpos=xpos+cm;
		else if(*navi_pointer=='N')
		ypos=ypos-cm;
		else if(*navi_pointer=='S')
		ypos=ypos+cm;
		}
	}
}
//Function to configure ports to enable robot's motion
void motion_pin_config (void)
{
	DDRA = DDRA | 0x0F;
	PORTA = PORTA & 0xF0;
	DDRL = DDRL | 0x18;   //Setting PL3 and PL4 pins as output for PWM generation
	PORTL = PORTL | 0x18; //PL3 and PL4 pins are for velocity control using PWM.
	OCR5A=0x00FF;
	OCR5B=0x00FF;
}

void left_encoder_pin_config (void)
{
	DDRE  = DDRE & 0xEF;  //Set the direction of the PORTE 4 pin as input
	PORTE = PORTE | 0x10; //Enable internal pull-up for PORTE 4 pin
}

void right_encoder_pin_config (void)
{
	DDRE  = DDRE & 0xDF;  //Set the direction of the PORTE 4 pin as input
	PORTE = PORTE | 0x20; //Enable internal pull-up for PORTE 4 pin
}

void port_init()
{
	motion_pin_config(); //robot motion pins config
	left_encoder_pin_config(); //left encoder pin config
	right_encoder_pin_config(); //right encoder pin config
}

void motion_set (unsigned char Direction)
{
	unsigned char PortARestore = 0;

	Direction &= 0x0F; 		// removing upper nibbel for the protection
	PortARestore = PORTA; 		// reading the PORTA original status
	PortARestore &= 0xF0; 		// making lower direction nibbel to 0
	PortARestore |= Direction; // adding lower nibbel for forward command and restoring the PORTA status
	PORTA = PortARestore; 		// executing the command
}

void left (void) //Left wheel backward, Right wheel forward
{
	motion_set(0x05);
}

void right (void) //Left wheel forward, Right wheel backward
{
	motion_set(0x0A);
}

void soft_left (void) //Left wheel stationary, Right wheel forward
{
	motion_set(0x04);
}

void soft_right (void) //Left wheel forward, Right wheel is stationary
{
	motion_set(0x02);
}

void stop (void)
{
	motion_set(0x00);
	//_delay_ms(1000);
}

void angle_rotate(unsigned int Degrees)
{
	raftaar(255,249);
	float ReqdShaftCount = 0;
	unsigned long int ReqdShaftCountInt = 0;
	if(node_num==15 || node_num==16 || node_num==17)
	ReqdShaftCount = (float) Degrees/ 4.60;
	else if(node_num==6 && r_node==21 && *navi_pointer=='W')
	{
		ReqdShaftCount = (float) Degrees/ 3.4;
	}
	else if(node_num==7 && path_index==2)
	{
		ReqdShaftCount = (float) Degrees/ 3.4;
	}
	else
	ReqdShaftCount = (float) Degrees/ 4.090; // division by resolution to get shaft count
	ReqdShaftCountInt = (unsigned int) ReqdShaftCount;
	r_encode = 0;
	l_encode = 0;
	double r,l;
	tempx=xpos;
	tempy=ypos;
	while (1)
	{
		if((r_encode >= ReqdShaftCountInt) | (l_encode >= ReqdShaftCountInt))
		break;
	}
	stop(); //Stop robot
	navigate();
}

void left_degrees(unsigned int Degrees)
{
	// 88 pulses for 360 degrees rotation 4.090 degrees per count
	navi=navi+Degrees;
	left(); //Turn left
	angle_rotate(Degrees);
	if(node_num==7 && path_index==2)
	{
		right();
		_delay_ms(300);
		stop();
	}
	while(digital[2]<15 && digital[1]<15 && digital[3]<15)
	{
		raftaar(180,174);
		left();
	}
	stop();
}
void right_degrees(unsigned int Degrees)
{
	// 88 pulses for 360 degrees rotation 4.090 degrees per count
	navi=navi-Degrees;
	right(); //Turn right
	angle_rotate(Degrees);
	while(digital[2]<15 && digital[3]<15 && digital[1]<15)
	{
		raftaar(180,174);
		right();
	}
	stop();
}
void soft_left_degrees(unsigned int Degrees)
{
	navi=navi+Degrees;
	// 176 pulses for 360 degrees rotation 2.045 degrees per count
	soft_left(); //Turn soft left
	Degrees=Degrees*2;
	angle_rotate(Degrees);
}
void soft_right_degrees(unsigned int Degrees)
{
	navi=navi-Degrees;
	// 176 pulses for 360 degrees rotation 2.045 degrees per count
	soft_right();  //Turn soft right
	Degrees=Degrees*2;
	angle_rotate(Degrees);
}
void INT_position(void)
{
	cli(); //Clears the global interrupt
	port_init();  //Initializes all the ports
	EICRB = EICRB | 0x08; // INT5 is set to trigger with falling edge
	EIMSK = EIMSK | 0x20; // Enable Interrupt INT5 for right position encoder
	EICRB = EICRB | 0x02; // INT4 is set to trigger with falling edge
	EIMSK = EIMSK | 0x10; // Enable Interrupt INT4 for left position encoder
	sei();   // Enables the global interrupt
}
void servo_config(void)
{
	cli();
	TCNT1=0x0000; // set starting value of counter
	ICR1=1150; // set top value of counter
	TCCR1A=0b10101010; // counter configuring
	TCCR1B=0b00011100;
	DDRB=DDRB|0b11100000; // set OC pins as output pins
	PORTB=PORTB|0b1110000;
	OCR1A=1150; // to free the servo
	OCR1B=1150;
	OCR1C=1150;
	sei();
}
void servo1_mov(int degree)
{

	if(node_num==13)
	OCR1A=((degree/1.89)+25);
	else
	OCR1A=ceil(((degree/1.89)+25));
	ser1=degree;
}
void servo2_mov(int degree)
{
	OCR1B=ceil(((degree/1.89)+25));
	ser2=degree;
}
void servo2_mov_spe(int degree)
{
	if(ser2>degree)
	{
		while(ser2>degree)
		{
			servo2_mov(ser2);
			_delay_ms(50);
			ser2=ser2-3;
		}
	}
	else
	{
		while(ser2<degree)
		{
			servo2_mov(ser2);
			_delay_ms(50);
			ser2=ser2+3;
		}
	}
}
void servo1_free(void)
{
	OCR1A=1150;
}
void servo2_free(void)
{
	OCR1B=1150;
}
void pick(void)
{	servo2_mov(3);
	_delay_ms(1000);
}
void pick_waste(void)
{
	servo2_mov(5);
	_delay_ms(1000);
}
void chhod_de(void)
{
	servo2_mov(45);
	_delay_ms(500);
	servo2_free();
}
void ADC_config(void)
{
	cli();
	TCCR3A=0x00;
	TCCR3B=0x02; // with clock setting 8
	TCCR3C=0x00;
	TIMSK3=0x01; // to enable timer overflow interrupt
	DDRF = 0x00; //set PORTF direction as input
	PORTF = 0x00; //set PORTF pins floating
	DDRK = 0x00; //set PORTK direction as input
	PORTK = 0x00; //set PORTK pins floating
	ADCSRA = 0x00;
	ADCSRB = 0x00;		//MUX5 = 0
	ADMUX = 0x20;		//Vref=5V external --- ADLAR=1 --- MUX4:0 = 0000
	ACSR = 0x80;
	ADCSRA = 0x86;		//ADEN=1 --- ADIE=1 --- ADPS2:0 = 1 1 0
}
int getdata(int Ch)
{
	int a;
	if(Ch>7)
	{
		ADCSRB = 0x08;
	}
	Ch = Ch & 0x07;
	ADMUX= 0x20| Ch;
	ADCSRA = ADCSRA | 0x40;		//Set start conversion bit
	while((ADCSRA&0x10)==0);	//Wait for ADC conversion to complete
	a=ADCH;
	ADCSRA = ADCSRA|0x10; //clear ADIF (ADC Interrupt Flag) by writing 1 to it
	ADCSRB = 0x00;
	return a;
}
int sharp(int adc_reading)
{
	float distance;
	int distanceInt;
	distance = (int)(10.00*(2799.6*(1.00/(pow(adc_reading,1.1546)))));
	distanceInt = (int)distance;
	if(distanceInt>800)
	{
		distanceInt=800;
	}
	return distanceInt;
}
void navigate(void) //To navigate robot
{
	cli();
	if(navi==0)
	navi_pointer="East ";
	else if(abs(navi)==270)
	{
		if(navi>0)
		navi_pointer="South";
		else
		navi_pointer="North";
	}
	else if(abs(navi)==180)
	{
		navi_pointer="West ";
	}
	else if(abs(navi)==90)
	{
		if(navi>0)
		navi_pointer="North";
		else
		navi_pointer="South";
	}
	lcd_cursor(2,12);
	lcd_string(navi_pointer);
	lcd_cursor(2,1);
	lcd_string("Node:-");
	lcd_print(2,7,node_num,2);
	lcd_cursor(1,1);
	lcd_string("A:");
	lcd_print(1,3,A,1);
	lcd_wr_char(' ');
	lcd_string("B:");
	lcd_print(1,7,B,1);
	lcd_wr_char(' ');
	lcd_string("C:");
	lcd_print(1,11,C,1);
	lcd_wr_char(' ');
	lcd_string("I:");
	lcd_print(1,15,IP,1);
	lcd_wr_char(' ');
	sei();
}

ISR(TIMER3_OVF_vect) // Timer 2 overflow interrupt to get digital value
{
	int i=0;
	for(i=1;i<4;i++)
	digital[i]=getdata(i);
	digital[11]=getdata(11);
	if(node_num<10)
	Area='C';
	else
	Area='I';
}
void line_following(void) //right=digital[1];middel=digital[2];left=digital[3]
{
	if (digital[2]>60 || (digital[1]>15 && digital[2]>15))
	{
		stop();
		node_behave(node_num,*navi_pointer);
	}
	else if(digital[2]>15 && (digital[1]>15 || digital[3]>15))
	
	{	stop();
		node_behave(node_num,*navi_pointer);
	}
	else if(digital[1]>15 && digital[3]<15)
	{
		raftaar(180,174);
		right();
	}
	else if(digital[1]<15 && digital[3]>15)
	{
		raftaar(180,174);
		left();
	}
	else
	{
		raftaar(255,249);
		motion('f');
	}
}
void node_behave(void) //How the robot behave when it detects a node
{
	navigate();
	if(node_num==7 && r_node==22 && path[path_index]!='\0')
	{
		distance('f',8.5,'o');
		if(path_index==5 || path_index==6)
		while(*navi_pointer!=path[path_index])
		{
			right();
			navi=navi-90;
			angle_rotate(45);
			while(digital[2]<15 && digital[3]<15)
			{
				right();
			}
			stop();
		}
		else
		while(*navi_pointer!=path[path_index])
		{
			left();
			navi=navi+90;
			angle_rotate(100);
		}			
		stop();
		path_index++;
	}
	else if(path[path_index]!='\0')
	{
		if((node_num==6 && *navi_pointer=='E' && r_node!=21) ||(node_num==16 && *navi_pointer=='W') ||(node_num==15 && *navi_pointer=='W') ||(node_num==17 && *navi_pointer=='W') )
		distance('f',3,'o');
		else
		distance('f',8.5,'o');
		if((*navi_pointer-path[path_index])==-9 || (*navi_pointer-path[path_index])==4 || (*navi_pointer-path[path_index])==14) //-9,4,14 are ASCII values for 270 degree while rotating in rightwards
			while(*navi_pointer!=path[path_index])
				{	left_degrees(90);}
		else if(node_num==3)
			while(*navi_pointer!=path[path_index])
				right_degrees(180);
		else if(abs(*navi_pointer-path[path_index])==5 || abs(*navi_pointer-path[path_index])==18)
			while(*navi_pointer!=path[path_index])
				left_degrees(180);
		else
			while(*navi_pointer!=path[path_index])
			right_degrees(90);
		path_index++;

	}
	else
	{
		node_num=r_node;
		navigate();
		if(node_num==15 || node_num==16 || node_num==17)
		{
			if((A+B+C)!=1 && colo_found==0)
			{
				left(); //Turn left
			angle_rotate(45);
			distance('f',13,'o');
			right(); //Turn left
			angle_rotate(170);
			stop();
			color_sensor();
			if(node_num==15)
			color_dep[0]=colo;
			if(node_num==16)
			color_dep[1]=colo;
			if(node_num==17)
			color_dep[2]=colo;
			left(); //Turn left
			angle_rotate(170);
			distance('b',11,'o');
			while(digital[2]<15 && digital[1]<15 && digital[3]<15)
			{
				raftaar(255,249);
				right();
			}
			right();
			angle_rotate(25);
			stop();}
			if(colo==color[color_index-1] || (A+B+C)==1)
			{
				servo1_mov(10);
				_delay_ms(1000);
				servo2_mov(45);
				_delay_ms(100);
				servo1_mov(80);
				_delay_ms(1000);
				servo2_free();
				if(node_num==15)
				A--;
				if(node_num==16)
				B--;
				if(node_num==17)
				C--;
				path_find(10);
				distance('b',6,'o');
			}
			else
			{
				distance('b',6,'o');
				if(A==1 && node_num!=15)
				enq_end(15);
				else if(C==1)
				enq_end(17);
			}
		}
		if(node_num==1)
		{
			distance('f',10,'o');
			left();
			navi=navi+90;
			angle_rotate(105);
			stop();
			if(w1==2)
			{
				distance('f',3,'o');
				servo1_mov(16);
				_delay_ms(1000);
				servo2_mov(1.5);
				_delay_ms(1000);
				servo1_mov(130);
				_delay_ms(1100);
				servo1_free();
			}
			else if(w1==1)
			{
				distance('f',3,'o');
				servo1_mov(11);
				_delay_ms(1000);
				servo2_mov(1.5);
				_delay_ms(1000);
				servo1_mov(130);
				_delay_ms(1100);
				servo1_free();
			}
			w1--;
			distance('b',14,'o');
			enq_end(4);
		}

		if(node_num==13)
		{
			if(w5!=0)
			{
				distance('f',12,'o');
				if(w5==2)
				{
					servo1_mov(16);
					_delay_ms(1000);
					servo2_mov(1.5);
					_delay_ms(1000);
					servo1_mov(130);
					_delay_ms(1100);
					servo1_free();
				}
				else if(w5==1)
				{
					servo1_mov(11);
					_delay_ms(1000);
					servo2_mov(1.5);
					_delay_ms(1000);
					servo1_mov(130);
					_delay_ms(1100);
					servo1_free();
				}
				w5--;
				distance('b',14,'o');
				enq_end(14);
			}
			else
			{
				distance('f',11,'o');
				left();
				navi=navi+90;
				angle_rotate(97);
				stop();
				if(w4==2)
				{
					distance('f',4,'o');
					servo1_mov(16);
					_delay_ms(1000);
					servo2_mov(1.5);
					_delay_ms(1000);
					servo1_mov(130);
					_delay_ms(1100);
					servo1_free();
				}
				else if(w4==1)
				{
					distance('f',4,'o');
					servo1_mov(11);
					_delay_ms(1000);
					servo2_mov(1.5);
					_delay_ms(1000);
					servo1_mov(130);
					_delay_ms(1100);
					servo1_free();
				}
			w4--;
			distance('b',14,'o');
			enq_end(14);
			}
		}

		if(node_num==3)
		{
			distance('f',12.5,'o');
			if(w2==2)
			{
				servo1_mov(16);
				_delay_ms(1000);
				servo2_mov(1.5);
				_delay_ms(1000);
				servo1_mov(130);
				_delay_ms(1100);
				servo1_free();
			}
			else if(w2==1)
			{
				distance('f',1,'o');
				servo1_mov(10);
				_delay_ms(1000);
				servo2_mov(3);
				_delay_ms(1000);
				servo1_mov(130);
				_delay_ms(1100);
				servo1_free();
			}
			w2--;
			distance('b',14.5,'o');
			enq_end(4);
		}
		if(node_num==12)
		{
			distance('f',12,'o');
			if(w3==2)
			{
				servo1_mov(16);
				_delay_ms(1000);
				servo2_mov(1.5);
				_delay_ms(1000);
				servo1_mov(130);
				_delay_ms(1100);
				servo1_free();
			}
			else if(w3==1)
			{
				distance('f',1,'o');
				servo1_mov(11);
				_delay_ms(1000);
				servo2_mov(1.5);
				_delay_ms(1000);
				servo1_mov(130);
				_delay_ms(1100);
				servo1_free();
			}
			w3--;
			distance('b',14,'o');
			enq_end(14);
		}
		if(node_num==6)
		{
			int i;
			if(IP!=1)
			{
				distance('b',3,'0');
				if(IP==3)
				{
					distance('f',2,'0');
					servo1_mov(37);
					_delay_ms(1000);
					pick_waste();
					servo1_mov(80);
					_delay_ms(1000);
					left_degrees(180);
					servo1_mov(0);
					_delay_ms(1000);
					color_sensor();
					color[color_index]=colo;
					servo1_mov(80);
					_delay_ms(100);
					if(B==1)
					path_find(16);
					else if(A==1)
					path_find(15);
					else if(C==1)
					path_find(17);
					path_index++;
					color_index++;
				}
			if(IP==2)
				{
					distance('f',2,'o');
					servo1_mov(25);
					_delay_ms(1000);
					pick_waste();
					servo1_mov(80);
					_delay_ms(1000);
					left_degrees(180);
					servo1_mov(0);
					_delay_ms(1000);
					color_sensor();
					color[color_index]=colo;
					servo1_mov(80);
					_delay_ms(100);
					int a=0;
					for(i=0;i<4;i++)
					{
						if(color[color_index]==color_dep[i])
						{
							colo_found++;
							path_find(15+i);
						}
						if(color_dep[i]!='\0')
						a++;
					}
					if(a>2)
					colo_found++;
					if(path[path_index]=='\0')
					{
						if(B==1 && color_dep[1]=='\0')
						path_find(16);
						else if(A==1 && color_dep[0]=='\0')
						path_find(15);
						else if(C==1 && color_dep[2]=='\0')
						path_find(17);
					}
					path_index++;
					color_index++;
				}
					IP--;
			}
			else
			{
				distance('f',3,'o');
				color_sensor();
				distance('b',3,'o');
				if(colo!='\0')
				{
					color[color_index]=colo;
					servo1_mov(0);
					_delay_ms(1000);
					pick_waste();
					servo1_mov(80);
					_delay_ms(1000);
					if(B==1)
					path_find(16);
					else if(A==1)
					path_find(15);
					else if(C==1)
					path_find(17);
					color_index++;
				}
				else
				{
					left_degrees(180);
					raftaar(255,249);
					while(digital[2]<50)
					{
						motion('b');
					}
					enq_end(7);
					enq_end(21);
				}

			}

		}
		if(node_num==7)
		{
			distance('f',3,'o');
			color_sensor();
			distance('b',3,'o');
			if(colo!='\0')
			{
				color[color_index]=colo;
				servo1_mov(0);
				_delay_ms(1000);
				pick_waste();
				servo1_mov(80);
				_delay_ms(1000);
				if(B==1)
				path_find(16);
				else if(A==1)
				path_find(15);
				else if(C==1)
				path_find(17);
				color_index++;
			}
			else
			{
				left();
				navi=navi+180;
				angle_rotate(135);
				while(digital[1]<15 && digital[2]<15 && digital[3]<15)
				{
					left();
				}
				stop();
				raftaar(255,249);
				while(digital[2]<50)
				{
					motion('b');
				}
				path_find(22);
				path_index=path_index+4;
				enq_end(8);
			}
		}
		if(node_num==8)
		{
			distance('f',3,'o');
			color_sensor();
			distance('b',3,'o');
			if(colo!='\0')
			{
				color[color_index]=colo;
				servo1_mov(0);
				_delay_ms(1000);
				pick_waste();
				servo1_mov(80);
				_delay_ms(1000);
				if(B==1)
				path_find(16);
				else if(A==1)
				path_find(15);
				else if(C==1)
				path_find(17);
				color_index++;
			}
			else
			{
				left_degrees(180);
				raftaar(255,249);
				while(digital[2]<50)
				{
					motion('b');
				}
				path_find(23);
				enq_end(9);
			}
		}
		if(node_num==9)
		{
			distance('f',3,'o');
			color_sensor();
			distance('b',3,'o');
			if(colo!='\0')
			{
				color[color_index]=colo;
				servo1_mov(0);
				_delay_ms(1000);
				pick_waste();
				servo1_mov(80);
				_delay_ms(1000);
				if(B==1)
				path_find(16);
				else if(A==1)
				path_find(15);
				else if(C==1)
				path_find(17);
				color_index++;
			}
			else
			{
				left_degrees(180);
				raftaar(255,249);
				while(digital[2]<50)
				{
					motion('b');
				}
				enq_end(0);
				enq_end(6);
			}
		}
		if(node_num==4)
		{
			distance('b',4,'o');
			servo1_mov(66);
			_delay_ms(1000);
			servo2_mov(45);
			_delay_ms(500);
			servo1_mov(90);
			left();
			navi=navi+180;
			angle_rotate(180);
			path_find(0);
			path_index++;
			distance('b',4,'o');

		}
		if(node_num==14)
		{
			distance('b',4,'o');
			servo1_mov(66);
			_delay_ms(1000);
			servo2_mov(45);
			_delay_ms(500);
			servo1_mov(90);
			left();
			navi=navi+180;
			angle_rotate(180);
			path_find(10);
			path_index++;
			distance('b',4,'o');
		}
		if(node_num==0)
		{
			if(*navi_pointer!='W')
			{
				distance('f',11,'o');
				if((*navi_pointer-'W'==-9) || (*navi_pointer-'W')==4 || (*navi_pointer-'W')==14) //-9,4,14 are ASCII values for 270 degree while rotating in rightwards
				while(*navi_pointer!='W')
				left_degrees(90);
				else if(abs(*navi_pointer-'W')==5 || abs(*navi_pointer-'W')==18)
				while(*navi_pointer!='W')
				right_degrees(180);
				else
				while(*navi_pointer!='W')
				right_degrees(90);
				distance('b',11,'o');
			}
			if(sharp(digital[11])>300)
			{
				bridge=Area;
			}
			else
			{
				bridge='I';
				if(w2==0)
				enq_end(1);
				else
				enq_end(3);
			}
				navigate();
				if(ser1!=180)
				{servo1_mov(80);
				_delay_ms(800);}
		}
		if(node_num==10)
		{
			if(*navi_pointer!='E')
			{
				distance('f',11,'o');
				if((*navi_pointer-'E'==-9) || (*navi_pointer-'E')==4 || (*navi_pointer-'E')==14) //-9,4,14 are ASCII values for 270 degree while rotating in rightwards
				while(*navi_pointer!='E')
				left_degrees(90);
				else if(abs(*navi_pointer-'E')==5 || abs(*navi_pointer-'E')==18)
				while(*navi_pointer!='E')
				right_degrees(180);
				else
				while(*navi_pointer!='E')
				right_degrees(90);
				distance('b',12,'o');
			}
			if(sharp(digital[11])>300)
			bridge=Area;
			else
			{
				bridge='C';
				if(w3!=0)
				enq_end(12);
				else
				enq_end(13);
			}
			navigate();
			if(ser1!=180)
			{servo1_mov(80);
			_delay_ms(800);}
		}

		if(que_length!=0 && path[path_index]=='\0')
		{
			path_find(end->num);
			dequeue();
		}
		else if(path[path_index]=='\0')
		{
			buzzer(1);
			_delay_ms(2000);
			buzzer(0);
			exit(1);
		}
	}
}

void color_sensor_pin_config(void)
{
	DDRD  = DDRD | 0xFE; //set PD0 as input for color sensor output
	PORTD = PORTD | 0x01;//Enable internal pull-up for PORTD 0 pin
}

void clrport_init(void)
{
	color_sensor_pin_config();//color sensor pin configuration
}

void color_sensor_pin_interrupt_init(void) //Interrupt 0 enable
{
	cli(); //Clears the global interrupt
	EICRA = EICRA | 0x02; // INT0 is set to trigger with falling edge
	EIMSK = EIMSK | 0x01; // Enable Interrupt INT0 for color sensor
	sei(); // Enables the global interrupt
}

//ISR for color sensor
ISR(INT0_vect)
{
	pulse++; //increment on receiving pulse from the color sensor
}

void init_devices(void)
{
	cli(); //Clears the global interrupt
	clrport_init();  //Initializes all the ports
	color_sensor_pin_interrupt_init();
	sei();   // Enables the global interrupt
}

//Filter Selection
void filter_red(void)    //Used to select red filter
{
	//Filter Select - red filter
	PORTD = PORTD & 0xBF; //set S2 low
	PORTD = PORTD & 0x7F; //set S3 low
}

void filter_green(void)	//Used to select green filter
{
	//Filter Select - green filter
	PORTD = PORTD | 0x40; //set S2 High
	PORTD = PORTD | 0x80; //set S3 High
}

void filter_blue(void)	//Used to select blue filter
{
	//Filter Select - blue filter
	PORTD = PORTD & 0xBF; //set S2 low
	PORTD = PORTD | 0x80; //set S3 High
}



//Color Sensing Scaling
void color_sensor_scaling()		//This function is used to select the scaled down version of the original frequency of the output generated by the color sensor, generally 20% scaling is preferable, though you can change the values as per your application by referring datasheet
{
	//Output Scaling 20% from datasheet
	//PORTD = PORTD & 0xEF;
	PORTD = PORTD | 0x10; //set S0 high
	//PORTD = PORTD & 0xDF; //set S1 low
	PORTD = PORTD | 0x20; //set S1 high
}

void red_read(void) // function to select red filter and display the count generated by the sensor on LCD. The count will be more if the color is red. The count will be very less if its blue or green.
{
	//Red
	filter_red(); //select red filter
	pulse=0; //reset the count to 0
	_delay_ms(100); //capture the pulses for 100 ms or 0.1 second
	red = pulse;  //store the count in variable called red
}

void green_read(void) // function to select green filter and display the count generated by the sensor on LCD. The count will be more if the color is green. The count will be very less if its blue or red.
{
	//Green
	filter_green(); //select green filter
	pulse=0; //reset the count to 0
	_delay_ms(100); //capture the pulses for 100 ms or 0.1 second
	green = pulse;  //store the count in variable called green
}

void blue_read(void) // function to select blue filter and display the count generated by the sensor on LCD. The count will be more if the color is blue. The count will be very less if its red or green.
{
	//Blue
	filter_blue(); //select blue filter
	pulse=0; //reset the count to 0
	_delay_ms(100); //capture the pulses for 100 ms or 0.1 second
	blue = pulse;  //store the count in variable called blue

}
void color_sensor(void)
{
	red_read();
	blue_read();
	green_read();
	if(red<th_color && blue<th_color && green<th_color)
	colo='\0';
	else
	{
		if(red>blue && red>green)
		colo='R';
		else if(blue>red && blue>green)
		colo='B';
		else if(green>red && green>blue)
		colo='G';
	}
	lcd_cursor(2,10);
	lcd_wr_char(colo);
}
int main(void)
{
	struct_config();
	lcd_port_config();
	lcd_init();
	INT_position();
	raftaar_config();
	servo_config();
	ADC_config();
	init_devices();
	color_sensor_scaling();
	navigate();
	servo1_mov(80);
	_delay_ms(500);
	chhod_de();
	enqueue(6);
	enqueue(0);
	enqueue(6);
	enqueue(0);
	enqueue(6);
	while(1)
	{
		line_following();
		if(A+B+C==0)
		{
			buzzer(1);
			_delay_ms(5000);
			buzzer(0);
			_delay_ms(500);
			break;
		}
	}
	/*node_num==7;
	path_find(22);
	lcd_cursor(1,1);
	while(path[path_index+3]!='\0')
	{
		lcd_wr_char(path[path_index+3]);
		path_index++;
	}*/
}

